"""
Django settings for socialsphere project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d@yb5klvp=%$6jt0)txx2sy+n_n%^1@4jj2v!9o%i%)0xte@zr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialsphere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialsphere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'frontend',
    BASE_DIR / 'core' / 'static',   # custom admin CSS + JS
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─────────────────────────────────────────────────────────────────────────────
# JAZZMIN — Premium Admin Dashboard Configuration
# Styled to match SocialSphere's dark-indigo glassmorphism design system
# ─────────────────────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {

    # ── Branding ──────────────────────────────────────────────────────────────
    "site_title":   "SocialSphere Admin",
    "site_header":  "SocialSphere",
    "site_brand":   "⬡ SocialSphere",
    "welcome_sign": "Welcome to SocialSphere Mission Control",
    "copyright":    "© 2026 SocialSphere — Crafted with ❤️",

    # ── Search ────────────────────────────────────────────────────────────────
    "search_model": ["auth.User", "core.Post", "core.Comment"],

    # ── Top Navigation Bar ────────────────────────────────────────────────────
    "topmenu_links": [
        {"name": "Dashboard",  "url": "admin:index",          "permissions": ["auth.view_user"]},
        {"name": "Live Site",  "url": "/",                    "new_tab": True},
        {"name": "Posts",      "url": "/admin/core/post/"},
        {"name": "Comments",   "url": "/admin/core/comment/"},
        {"name": "Users",      "url": "/admin/auth/user/"},
    ],

    # ── User Menu (top-right) ─────────────────────────────────────────────────
    "usermenu_links": [
        {"name": "View Live Site", "url": "/", "new_tab": True, "icon": "fas fa-globe"},
        {"model": "auth.user"},
    ],

    # ── Sidebar ───────────────────────────────────────────────────────────────
    "show_sidebar":          True,
    "navigation_expanded":   True,
    "hide_apps":             [],
    "hide_models":           [],

    "order_with_respect_to": [
        "auth",
        "auth.user",
        "auth.Group",
        "core",
        "core.userprofile",
        "core.post",
        "core.comment",
        "core.like",
        "core.follow",
    ],

    "custom_links": {
        "core": [
            {
                "name":        "Analytics",
                "url":         "admin:index",
                "icon":        "fas fa-chart-line",
                "permissions": ["auth.view_user"],
            },
        ],
    },

    # ── Icons ─────────────────────────────────────────────────────────────────
    "icons": {
        "auth":             "fas fa-shield-alt",
        "auth.user":        "fas fa-users",
        "auth.Group":       "fas fa-layer-group",
        "core":             "fas fa-rocket",
        "core.userprofile": "fas fa-id-card",
        "core.post":        "fas fa-newspaper",
        "core.comment":     "fas fa-comments",
        "core.like":        "fas fa-heart",
        "core.follow":      "fas fa-user-plus",
    },
    "default_icon_parents":  "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    # ── UI Features ───────────────────────────────────────────────────────────
    "related_modal_active":  True,
    "custom_css":            "admin/css/custom_admin.css",
    "custom_js":             None,
    "use_google_fonts_cdn":  True,
    "show_ui_builder":       False,

    # ── Change-view UI ────────────────────────────────────────────────────────
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user":        "collapsible",
        "auth.group":       "vertical_tabs",
        "core.post":        "horizontal_tabs",
        "core.userprofile": "collapsible",
    },
}

# ── Jazzmin UI Theme — Dark mode optimized for our CSS overrides ──────────────
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text":          False,
    "footer_small_text":          False,
    "body_small_text":            False,
    "brand_small_text":           False,
    "brand_colour":               "navbar-dark",
    "accent":                     "accent-primary",
    "navbar":                     "navbar-dark",
    "no_navbar_border":           True,
    "navbar_fixed":               True,
    "layout_boxed":               False,
    "footer_fixed":               False,
    "sidebar_fixed":              True,
    "sidebar":                    "sidebar-dark-primary",
    "sidebar_nav_small_text":     False,
    "sidebar_disable_expand":     False,
    "sidebar_nav_child_indent":   True,
    "sidebar_nav_compact_style":  False,
    "sidebar_nav_legacy_style":   False,
    "sidebar_nav_flat_style":     False,
    "theme":                      "darkly",
    "dark_mode_theme":            "darkly",
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
    "actions_sticky_top": True,
}


